repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.3.0
  hooks:
  - id: trailing-whitespace
  - id: end-of-file-fixer
  - id: check-yaml
  - id: detect-private-key
  - id: check-merge-conflict
  - id: mixed-line-ending
    args: ['--fix=auto']
- repo: https://github.com/astral-sh/ruff-pre-commit
  rev: v0.0.279
  hooks:
  - id: ruff
    args: ["--fix"]
