FROM python:3.10-slim

WORKDIR /app

COPY . .

RUN pip install --upgrade pip
# Add any necessary system packages
RUN apt-get update && apt-get install -y --no-install-recommends <necessary-packages>

RUN pip install -r requirements.txt

CMD ["python", "main.py"]
